### ISSUE TITLE
Forcefields causing white screen & other artefacts

### ISSUE THREAD

**Issue by ryadblender** [michal1000w/GPUSmoke#2]
https://user-images.githubusercontent.com/71760318/113968619-41e37580-9855-11eb-97a6-4bb6719abedb.mp4

**Comment by ryadblender** [comment]
![image](https://user-images.githubusercontent.com/71760318/113968692-650e2500-9855-11eb-85b3-c3ce6abeab8b.png)

**Comment by michal1000w** [comment]
There should be "flame" attribute instead of "fire", however I think I may make another video about blender part of this simulator
![image](https://user-images.githubusercontent.com/19635319/113969452-5152c680-9835-11eb-9c31-715e9c188c5a.png)

**Comment by ryadblender** [comment]
Thanks i was doing the attributes wrong haha. btw here is my simple setup on whats happening with the force/wind

https://user-images.githubusercontent.com/71760318/113976748-5890c900-9863-11eb-947d-dad0d52a5466.mp4

**Comment by michal1000w** [comment]
Yeah, it's a weird bug. I mean I know about it but had no time to dive deeper to why it's happening but it's gone after restarting the simulation so I've decided to release it earlier. Maybe in the next release it will be fixed but it may be complicated

**Comment by ryadblender** [comment]
hi I figured out why the whitescreen problem was happening. if you have any type of force emitter intersecting the domain, it causes the whole domain turn white. its a fun way to find out the invisible domain size tho 🥉

**Comment by michal1000w** [comment]
From yesterday I'm trying to find the bug however for now I don't know why it's happening

**Comment by ryadblender** [comment]
hope you'll figure it out soon. maybe you could restrict the emitter to be closer to the domain edges. IDK anything about coding but this may be a fix.

**Comment by michal1000w** [comment]
Alright I fixed it. It was a dividing by 0 problem in CUDA kernels. Now after some initial tests it seems to work fine (hopefully)
https://1drv.ms/u/s!AimiuF_EfxPTmKAcOE244yyMgr-NOQ?e=CVjqMz
Here is a new version (tomorrow there will be an official release)
